version: '3'

# описываеем обстракции программ
services:
  db:
    image: postgres:16
    container_name: db_app
    command: -p 1212
    expose:
      - 1212
    env_file:
      - ./core/.env-non-dev
    volumes:
       - /var/lib/postgresql/data


  redis:
    image: redis:7
    hostname: redis
    env_file:
      - ./core/.env-non-dev
    container_name: redis
    command: --port 6374
    expose:
      - 6374
    ports:
        - 6374:6374
  
  app:
    build:
      context: .
    env_file:
      - ./core/.env-non-dev
    container_name: news
    command: ['./docker/app.sh']
    ports:
      - 8001:8000
    depends_on:
      - db
      - redis


  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    env_file:
      - ./core/.env-non-dev
    ports:
        - 5673:5673
        - 15672:15672
    expose:
      - 5673

    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

  celery:
    build:
      context: .
    env_file:
      - ./core/.env-non-dev
    container_name: celery
    command: ['./docker/selery.sh', 'celery']
    volumes:
      - /logs/celery.log

    depends_on:
      - redis
      - rabbitmq
  
  flower:
    build:
      context: .
    env_file:
      - ./core/.env-non-dev
    container_name: flower
    command: ['./docker/selery.sh', 'flower']
    depends_on:
      - celery
      - redis
      - rabbitmq
    ports:
      - 7777:5555
