"""Database creation

Revision ID: de4cff1e7943
Revises: 
Create Date: 2024-01-15 21:00:49.730950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision: str = 'de4cff1e7943'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('uid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('create_date', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('owner_uid', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_post_uid'), 'post', ['uid'], unique=False)
    op.create_table('comment',
    sa.Column('uid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('create_date', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('post_uid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('owner_uid', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['post_uid'], ['post.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_comment_uid'), 'comment', ['uid'], unique=False)
    op.create_table('view',
    sa.Column('uid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('post_uid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('owner_uid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['post_uid'], ['post.uid'], ),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('post_uid', 'owner_uid', name='unique')
    )
    op.create_index(op.f('ix_view_uid'), 'view', ['uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_view_uid'), table_name='view')
    op.drop_table('view')
    op.drop_index(op.f('ix_comment_uid'), table_name='comment')
    op.drop_table('comment')
    op.drop_index(op.f('ix_post_uid'), table_name='post')
    op.drop_table('post')
    # ### end Alembic commands ###
