"""remake token

Revision ID: 68ef22273897
Revises: 8048e80e04e1
Create Date: 2024-02-17 22:03:53.949179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '68ef22273897'
down_revision: Union[str, None] = '8048e80e04e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
import sqlalchemy_utils

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token', sa.Column('jti', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False))
    op.add_column('token', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('token', sa.Column('device_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False))
    op.drop_index('ix_token_token', table_name='token')
    op.drop_index('ix_token_uid', table_name='token')
    op.create_index(op.f('ix_token_jti'), 'token', ['jti'], unique=False)
    op.drop_column('token', 'token')
    op.drop_column('token', 'uid')
    op.drop_column('token', 'expires')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token', sa.Column('expires', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('token', sa.Column('uid', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('token', sa.Column('token', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_token_jti'), table_name='token')
    op.create_index('ix_token_uid', 'token', ['uid'], unique=False)
    op.create_index('ix_token_token', 'token', ['token'], unique=False)
    op.drop_column('token', 'device_id')
    op.drop_column('token', 'is_active')
    op.drop_column('token', 'jti')
    # ### end Alembic commands ###
